health/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'health'

urlpatterns = [
    path('', views.main, name="main"),
    path('register', views.register_user, name="register"),
    path('login', views.login_user, name="login"),
    path('logout', views.logout_user, name="logout"),

    path('update-profile', views.update_profile, name='update_profile'),
    path('recipes', views.recipes, name="recipes"),
    path('dashboard', views.dashboard, name='dashboard'),
    path('add-food', views.food_list, name='food_list'),

    path('user/api/<str:user_id>', views.api_profile, name="api_profile"),
    path('recipes/api/<str:category>', views.api_recipes, name="api_recipes"),
    path('send_message/<str:user_id>', views.app_message, name="app_message"),
    path('food/<str:food_id>', views.api_food, name='api_food'),
    path('all-foods', views.api_all_foods, name='api_all_foods'),
    path('food/user/created/<str:user_id>', views.api_food_creator, name='food_creator'),

    # path('password_reset',
    #  auth_views.PasswordResetView.as_view(template_name='health/password_reset.html', 
    #                                         email_template_name='health/password_reset_email.html'),
    #   name='reset_password'),

    # path('reset_password_sent/', 
    # auth_views.PasswordResetDoneView.as_view(template_name='health/passoword_reset_sent.html'), 
    # name='password_reset_done'),

    # path('reset/<uidb64>/<token>/', 
    # auth_views.PasswordResetConfirmView.as_view(template_name='health/passoword_reset_form.html'), 
    # name='password_reset_confirm'),

    # path('reset_password_complete/', 
    # auth_views.PasswordResetCompleteView.as_view(template_name='health/passoword_reset_done.html'), 
    # name='password_reset_complete'),
]

healthgain/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('health.urls')),
    
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Healthgain Admin"
admin.site.index_title = "All Tables"
admin.site.site_title = "Healthgain Administration"

health/forms.py
from django import forms
from django.forms import ModelForm, Textarea

from health.models import Main_food, Profile_user

class RegisterForm(forms.Form):
    username        = forms.CharField(max_length=100, widget=forms.TextInput(
                                        attrs={'class':'form__input', 'placeholder': 'Username'}))
    password        = forms.CharField(max_length=32, widget=forms.PasswordInput(
                                        attrs={'class': 'form__input', 'placeholder': 'Password'}))
    password_conf   = forms.CharField(max_length=32, widget=forms.PasswordInput(
                                        attrs={'class': 'form__input', 'placeholder': 'Repeat Password'}))
    email           = forms.EmailField(label="Email", max_length=150, widget=forms.EmailInput(
                                        attrs={'class': 'form__input', 'placeholder': 'Email'}))
    height          = forms.IntegerField(min_value=10, max_value=500, widget=forms.NumberInput(
                                        attrs={'class':'form__input', 'placeholder': 'height(cm)'}))                  
    weight          = forms.FloatField(min_value=10, max_value=500, widget=forms.NumberInput(
                                        attrs={'class': 'form__input', 'placeholder': 'weight'}))

class ProfileForm(ModelForm):
    
    class Meta:
        model = Profile_user
        fields = '__all__'
        exclude = ['user', 'favourite_foods']
        widgets = {
            'email': forms.EmailInput(attrs={'class':'form__input'}),
            'first_name': forms.TextInput(attrs={'class':'form__input'}),
            'last_name': forms.TextInput(attrs={'class':'form__input'}),
            'weight': forms.NumberInput(attrs={'class':'form__input'}),
            'height': forms.NumberInput(attrs={'class':'form__input'}),
            'age': forms.NumberInput(attrs={'class':'form__input'}),
            'weight_goal': forms.NumberInput(attrs={'class':'form__input'}),
        }

health/views.py
import json
from datetime import date, timedelta

from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect, reverse

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.db.models import Q
from django.views.decorators.csrf import csrf_exempt

from .forms import RegisterForm, ProfileForm
from .models import Main_food, Profile_user, Daily_food, Recipes, Messages


# Main page
def main(request):

    if request.user.is_authenticated:
        # Get user logged
        user_logged = User.objects.get(pk=request.user.id)

        # Get todays day and get the day before
        tday = date.today()
        tdelta = timedelta(days=1)
        yesterday = tday - tdelta

        # Get foods from today and yesterday
        today_food = user_logged.consumed_food.filter(date_consumed=date.today())
        yesterday_food = user_logged.consumed_food.filter(date_consumed=yesterday)

        # Store results of each day into variables
        today_nutrition = {
            'date': tday,
            'calories': 0,
            'total_fat': 0,
            'carbs': 0,
            'fiber': 0,
            'protein':0
            }

        yesterday_nutrition = {
            'date': yesterday,
            'calories': 0,
            'total_fat': 0,
            'carbs': 0,
            'fiber': 0,
            'protein':0
            }

        for food in today_food:
            today_nutrition['calories'] += food.food.calories * food.weight / food.food.weight
            today_nutrition['total_fat'] += food.food.total_fat * food.weight / food.food.weight
            today_nutrition['carbs'] += food.food.carbs * food.weight / food.food.weight
            today_nutrition['fiber'] += food.food.fiber * food.weight / food.food.weight
            today_nutrition['protein'] += food.food.protein * food.weight / food.food.weight

        for food in yesterday_food:
            yesterday_nutrition['calories'] += food.food.calories * food.weight / food.food.weight
            yesterday_nutrition['total_fat'] += food.food.total_fat * food.weight / food.food.weight
            yesterday_nutrition['carbs'] += food.food.carbs * food.weight / food.food.weight
            yesterday_nutrition['fiber'] += food.food.fiber * food.weight / food.food.weight
            yesterday_nutrition['protein'] += food.food.protein * food.weight / food.food.weight

        context = {
            'today_food': today_nutrition,
            'yesterday_food': yesterday_nutrition
            }
        return render(request, "health/index.html", context)


    return render(request, "health/index.html")

# Register user
def register_user(request):

    if request.user.is_authenticated:
        return redirect('health:main')
    
    if request.method == "POST":

        form = RegisterForm(request.POST)

        if form.is_valid():

            username    = form.cleaned_data['username']
            password    = form.cleaned_data['password']
            password_1  = form.cleaned_data['password_conf']
            email       = form.cleaned_data['email']
            weight      = form.cleaned_data['weight']
            height      = form.cleaned_data['height']

            # If passwords don't match
            if password != password_1:
                message = "Password does not match"
                context = {'form': RegisterForm(), 'message': message }
                return render(request, "health/register.html", context)
            
            # Check if username already exists
            check_user = User.objects.filter(username=username)
            check_email = User.objects.filter(email=email)

            if len(check_user) >= 1 or len(check_email) >= 1:
                message = "Username already exists, try other" if len(check_user) >= 1 else "Email already exists, try other"
                context = {'form': RegisterForm(), 'message': message }
                return render(request, "health/register.html", context)

            # Create User
            user = User.objects.create_user(username=username, password=password, email=email)
            user.save()

            profile_update = Profile_user.objects.get(user=user)
            profile_update.weight = weight
            profile_update.height = height
            profile_update.save()

            messages.success(request, 'Account was created for ' + user.email)

            return redirect('health:login')

    form = RegisterForm()
    context = {'form': form }
    return render(request, "health/register.html", context)

# Login user
def login_user(request):

    if request.user.is_authenticated:
        return redirect('health:main')

    if request.method == "POST":
        
        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]

        # Check if user is in database
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return redirect('health:main')
        else:
            return render(request, "health/login.html", {
                "message": "Invalid username and/or password."
            })

    else:
        return render(request, "health/login.html")

# Logout user
def logout_user(request):
    logout(request)
    return redirect('health:main')

# Display recipes
def recipes(request):

    if request.method == 'POST':
        search = request.POST['search']

        recipes = Recipes.objects.filter(name__startswith=search)
        print(recipes)
        context = { 'recipes': recipes }
        return render(request, "health/recipes.html", context)

    return render(request, "health/recipes.html")

# API for message
@csrf_exempt
def app_message(request, user_id):

    if request.method == 'POST':

        data = json.loads(request.body)

        user = User.objects.get(pk=user_id)
        message = Messages(user=user, message=data['message_app'])
        message.save()

        return JsonResponse({"message": "Email sent successfully."}, status=201)

# Add food to main food table
@login_required(login_url='login')
def food_list(request):

    if request.method == 'POST':
        category    = request.POST['category']
        name        = request.POST['name']
        brand       = request.POST['brand']
        calories    = request.POST['calories']
        total_fat   = request.POST['total_fat']
        carbs       = request.POST['carbs']
        fiber       = request.POST['fiber']
        protein     = request.POST['protein']

        user = User.objects.get(pk=request.user.id)
        add_ = Main_food(name=name, brand=brand, category=category, calories=calories, total_fat=total_fat, carbs=carbs, fiber=fiber, protein=protein, creator=user)
        add_.save()

        return render(request, 'health/food-list.html')


    return render(request, 'health/food-list.html')

# Show user stats
@login_required(login_url='login')
def dashboard(request):

    # Get user
    user_ = User.objects.get(pk=request.user.id)

    if request.method == 'POST':
        if 'add-food' in request.POST:

            food_user = request.POST['food']
            weight = request.POST['weight']

            food = Main_food.objects.get(pk=food_user)

            daily = Daily_food(user=user_, food=food, category=food.category, weight=weight)
            daily.save()

            messages.success(request, 'Food added to your daily intake')

            return redirect('health:dashboard')

        elif 'date_query' in request.POST:
            
            date_daily = request.POST['date']

            date_query = Daily_food.objects.filter(date_consumed=date_daily)

            date_query_nutrition = {
                'date': date_daily,
                'calories': 0,
                'total_fat': 0,
                'carbs': 0,
                'fiber': 0,
                'protein':0
            }

            for food in date_query:
                date_query_nutrition['calories'] += food.food.calories * food.weight / food.food.weight
                date_query_nutrition['total_fat'] += food.food.total_fat * food.weight / food.food.weight
                date_query_nutrition['carbs'] += food.food.carbs * food.weight / food.food.weight
                date_query_nutrition['fiber'] += food.food.fiber * food.weight / food.food.weight
                date_query_nutrition['protein'] += food.food.protein * food.weight / food.food.weight

            # print(date_query)
            
        elif 'update_food' in request.POST:

            food_id = request.POST['food-id']
            new_weight = request.POST['new_weight']

            food = Daily_food.objects.get(pk=food_id)
            food.weight = new_weight
            food.save()
            print(new_weight)


    # Get profile
    profile_user = Profile_user.objects.get(user=user_)

    # Get todays day and get the day before
    tday = date.today()

    # Get foods from today and yesterday
    today_food = user_.consumed_food.filter(date_consumed=date.today())

    # Store results of each day into variables
    today_nutrition = {
        'date': tday,
        'calories': 0,
        'total_fat': 0,
        'carbs': 0,
        'fiber': 0,
        'protein':0
        }

    for food in today_food:
        today_nutrition['calories'] += food.food.calories * food.weight / food.food.weight
        today_nutrition['total_fat'] += food.food.total_fat * food.weight / food.food.weight
        today_nutrition['carbs'] += food.food.carbs * food.weight / food.food.weight
        today_nutrition['fiber'] += food.food.fiber * food.weight / food.food.weight
        today_nutrition['protein'] += food.food.protein * food.weight / food.food.weight
        
    try:

health/templates/health/food-list.html
{% extends 'health/layout.html' %}

{% load static %}

{% block content %}

    {% include 'health/nav-bar.html' %}

    <header class="header--food-list">
        <div class="header__title">
            Add to your favourites food list
        </div>

    </header>
    {% include 'health/pop-up-profile.html' %}


    <main class="food-list">

        <p class="paragraph">Add some foods to your list, so you can update your dashboard with the food you want.</p>
        <p class="paragraph">If you don't find the food you want, you can always create it.</p>

        <div class="food-list__create-food margin-top-large">

            <h2 class="heading-secondary">Create new food</h2>

            <form action="{% url 'health:food_list' %}" method="POST" class="form" enctype="multipart/form-data">

                {% csrf_token %}

                <label for="" class="form__label">Food or drink:</label>
                <select name="category" id="" class="form__input" required>
                    <option value="" disabled selected hidden></option>
                    <option value="food">Fodd</option>
                    <option value="drink">Drink</option>
                </select>
    
                <label for="" class="form__label">Name:</label>
                <input class="form__input" name="name" type="text" required>

                <label for="" class="form__label">Brand:</label>
                <input class="form__input" name="brand" type="text">
    
                <label for="" class="form__label">Calories (per 100g/ml):</label>
                <input class="form__input" name="calories" type="number" required>
    
                <label for="" class="form__label">Total fat (per 100g/ml):</label>
                <input class="form__input" name="total_fat" type="number" required>
    
                <label for="" class="form__label">Carbohydrate (per 100g/ml):</label>
                <input class="form__input" name="carbs" type="number" required>
    
                <label for="" class="form__label">Fiber (per 100g/ml):</label>
                <input class="form__input" name="fiber" type="number" required>
    
                <label for="" class="form__label">Protein (per 100g/ml):</label>
                <input class="form__input" name="protein" type="number" required>
    
                <input type="submit" class="btn--submit margin-top-medium">
            </form>
        </div>

        <div class="search-bar--box margin-top-large">
            <form action="#" class="search-bar" id="search-food" data-userId="{{ request.user.profile.id }}">
                <input type="text" class="search-bar__input" placeholder="Search for food or drink">
                <button type="submit" class="search-bar__button">
                    <i class="fas fa-search"></i>
                </button>
            </form>
        </div>
        
        <div class="food-list__toggle-box">
            <button class="food-list__toggle-box__button food-list-button" data-list="myList" data-user="{{ request.user.profile.id }}">My list</button>
            <button class="food-list__toggle-box__button food-list-button" data-list="allFoods" data-user="{{ request.user.profile.id }}">All foods</button>
            <button class="food-list__toggle-box__button food-list-button" data-list="created" data-user="{{ request.user.profile.id }}">Created</button>
        </div>


        <div class="food-list__list" id="food-list">

 
        </div>

        
    </main>

    {% include 'health/footer.html' %}

{% endblock %}

health/templates/health/index.html
{% extends 'health/layout.html' %}

{% load static %}

{% block content %}

    {% include 'health/nav-bar.html' %}

    <header class="header">

        {% if user.is_authenticated %}

            <div class="header__user-info">
                <p class="header__user-info__text">Missing:</p>
                <span class="header__user-info__number" id="missing-weight" data-userid="{{ request.user.profile.id }}"></span>
                <p class="header__user-info__text">Goal: {{ request.user.profile.weight_goal }} Kg</p>
            </div>

            {% include 'health/pop-up-profile.html' %}
        
        {% else %}

            <h1 class="header__slogan">
                Food is the ingredient that bind us together
            </h1>
            <a href="{% url 'health:recipes' %}" class="header__link-recipes">Check our recipes!</a>

        {% endif %}

    </header>

    <main class="main">

        {% if user.is_authenticated %}

            <!-- What user took previous day, and today -->
            <section class="section-intake">
                <h2 class="heading-secondary margin-bottom-large">Never forget about your previous day</h2>

                <table class="table--intake">
                    <tr class="table--intake__row">
                        <th class="table--intake__row__header"></th>
                        <th class="table--intake__row__header">{{ yesterday_food.date }}</th>
                        <th class="table--intake__row__header">{{ today_food.date }}</th>
                    </tr>

                    <tr class="table--intake__row">
                        <td class="table--intake__row__title">Calories</td>
                        <td class="table--intake__row__data">{{ yesterday_food.calories | floatformat }}</td>
                        <td class="table--intake__row__data">{{ today_food.calories | floatformat }}</td>
                    </tr>

                    <tr class="table--intake__row">
                        <td class="table--intake__row__title">Total Fat</td>
                        <td class="table--intake__row__data">{{ yesterday_food.total_fat | floatformat }}</td>
                        <td class="table--intake__row__data">{{ today_food.total_fat | floatformat }}</td>
                    </tr>

                    <tr class="table--intake__row">
                        <td class="table--intake__row__title">Carbohydrate</td>
                        <td class="table--intake__row__data">{{ yesterday_food.carbs | floatformat }}</td>
                        <td class="table--intake__row__data">{{ today_food.carbs | floatformat }}</td>
                    </tr>

                    <tr class="table--intake__row">
                        <td class="table--intake__row__title">Fiber</td>
                        <td class="table--intake__row__data">{{ yesterday_food.fiber | floatformat }}</td>
                        <td class="table--intake__row__data">{{ today_food.fiber | floatformat }}</td>
                    </tr>

                    <tr class="table--intake__row">
                        <td class="table--intake__row__title">Protein</td>
                        <td class="table--intake__row__data">{{ yesterday_food.protein | floatformat }}</td>
                        <td class="table--intake__row__data">{{ today_food.protein | floatformat }}</td>
                    </tr>

                </table>

                <a href="{% url 'health:dashboard' %}" class="btn btn--juicy margin-top-medium">Add food</a>
            </section>

            <!-- User suggest something for app -->
            <section class="section-app">
                <h2 class="heading-secondary margin-bottom-small">Mobile Apps</h2>
                <p class="paragraph margin-bottom-medium">We are currently developing our mobile app. Let us what features you would like to see in the app!</p>
                
                <div class="section-app__form">
                    <i class="fas fa-mobile-alt section-app__form__icon"></i>

                    <form class="form form--smaller" action="#" id="app-message">
                        {% csrf_token %}
                        <textarea class="form__textarea textarea-app" maxlength="300" name="" id="app-message-text-{{ request.user.id }}" cols="30" rows="5"></textarea>
                        <span class="form__max-carach">Max <span id="max-carach">300</span> characters.</span>
                        <input class="btn btn--grey margin-top-medium" type="submit" value="Send">
                    </form>

                    <i class="fas fa-cogs section-app__form__icon"></i>
                </div>

            </section>
        
        {% else %}

            <section class="section-features">
                <h2 class="heading-secondary margin-bottom-small">Features</h2>
                <p class="paragraph">Calorie reduced diets require a lot of information to perform optimally. In order to restrict caloric intake, but remain healthy, users of the diet must track their vitamin, mineral, and protein intakes with great care.</p>
                <p class="paragraph margin-bottom-large">We aim to provide a complete solution for the smart dieter.</p>


                <div class="features-cards">

                    <div class="features-cards__card">
                        <img src="{% static 'health/images/cronometer-icon-1.png' %}" class="features-cards__card__image" alt="" class="imagen">
                        <p class="features-cards__card__text">Easy to use, streamlined data entry</p>
                    </div>

                    <div class="features-cards__card">
                        <img src="{% static 'health/images/cronometer-icon-2.png' %}" class="features-cards__card__image" alt="" class="imagen">
                        <p class="features-cards__card__text">Track up to 300,000+ foods</p>
                    </div>

                    <div class="features-cards__card">
                        <img src="{% static 'health/images/cronometer-icon-3.png' %}" class="features-cards__card__image" alt="" class="imagen">
                        <p class="features-cards__card__text">Log your diet, exercise, biometrics and notes</p>
                    </div>

                    <div class="features-cards__card">
                        <img src="{% static 'health/images/cronometer-icon-4.png' %}" class="features-cards__card__image" alt="" class="imagen">
                        <p class="features-cards__card__text">Log your diet, exercise, biometrics and notes</p>
                    </div>

                    <div class="features-cards__card">
                        <img src="{% static 'health/images/cronometer-icon-5.png' %}" class="features-cards__card__image" alt="" class="imagen">
                        <p class="features-cards__card__text">Log your diet, exercise, biometrics and notes</p>
                    </div>

                    <div class="features-cards__card">
                        <img src="{% static 'health/images/cronometer-icon-6.png' %}" class="features-cards__card__image" alt="" class="imagen">
                        <p class="features-cards__card__text">Log your diet, exercise, biometrics and notes</p>
                    </div>
                    
                </div>


            </section>

            <section class="section-app">

                <h2 class="heading-secondary margin-bottom-small">Mobile Apps</h2>
                <p class="paragraph margin-bottom-medium">We are currently developing our mobile app. Let us what features you would like to see in the app!</p>
                
                <div class="section-app__form">
                    <i class="fas fa-mobile-alt section-app__form__icon"></i>
                    <div class="section-app__form__text">
                        <a href="{% url 'health:login' %}">Sign in</a>
                        <h3 class="heading-tertiary">And tell us what features you would like to have on the app</h3>
                    </div>
                    <i class="fas fa-cogs section-app__form__icon"></i>
                </div>

            </section>

        {% endif %}

    </main>

    {% include 'health/footer.html' %}
    
{% endblock %}

health/templates/health/login.html
{% extends 'health/layout.html' %}

{% load static %}

{% block content %}

    <div class="main-login">

        <div class="form-box">

            <h1 class="heading-primary">Log in</h1>

            <form action="{% url 'health:login' %}" method="POST" class="form">
                {% csrf_token %}
                <input type="text" name="username" placeholder="Username" class="form__input">
                <input type="password" name="password" placeholder="Password" class="form__input">
                <input type="submit" class="btn--submit" value="Log in">
            </form>

            <div class="form-box__info">
                <span>Not a member? <a href="{% url 'health:register' %}" class="form-box__info__link">Sign Up Now</a></span>
                <!-- <a href="" class="form-box__info__link">Forgot Password?</a> -->
            </div>
            

        </div>

        {% if messages %}
            {% for message in messages %}
                <p class="flash-message">{{ message }}</p>
            {% endfor %}
        {% endif %}

        <h2 class="heading-secondary margin-bottom-large">
            <a href="{% url 'health:main' %}" class="form-box--link-back">Go back to main page</a>
        </h2>

        <footer class="footer-small">
            <h3 class="heading-tertiary footer__title">Connect with us</h3>

            <div class="footer-small__connect">
                <a href="#" class="footer-small__connect--logo"><i class="fab fa-instagram"></i></a>
                <a href="#" class="footer-small__connect--logo"><i class="fab fa-facebook-f"></i></a>
                <a href="#" class="footer-small__connect--logo"><i class="fab fa-twitter"></i></a>
                <a href="#" class="footer-small__connect--logo"><i class="fab fa-youtube"></i></a>
                
            </div>

            <p class="footer-small__text">Copyright © by André Dias.</p>
            
        </footer>
    </div>

{% endblock %}

health/templates/health/nav-bar.html
<nav class="nav-bar">
    <a href="{% url 'health:main' %}">
        <span class="nav-bar__logo">HealthGain</span>
    </a>

    <i class="fas fa-bars nav-bar__icon" id="nav-bar-button" ></i>
    <div class="nav-bar__links" id="nav-bar-links">

        {% if user.is_authenticated %}
            <a href="#" class="nav-bar__link pop-up-link" data-popup="pop-up-profile">My Profile</a>
            <a href="{% url 'health:dashboard' %}" class="nav-bar__link">Dashboard</a>
            <a href="{% url 'health:food_list' %}" class="nav-bar__link">Food list</a>
            <a href="{% url 'health:recipes' %}" class="nav-bar__link">Check our Recipes</a>
            <a href="{% url 'health:logout' %}" class="nav-bar__link">Logout</a>
        {% else %}
            <a href="{% url 'health:recipes' %}" class="nav-bar__link">Check our Recipes</a>
            <a href="{% url 'health:login' %}" class="nav-bar__link">Login</a>
            <a href="{% url 'health:register' %}" class="nav-bar__link">Register</a>
        {% endif %}



    </div>
</nav>

health/templates/health/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'health:password_reset_confirm' uidb64=uid token=token %}

health/templates/health/password_reset_form.html
<h3>Enter new password</h3>

<p>Please enter your new password twice so we can verify you typed it in correctly.</p>

<form action="{% url 'health:password_reset_done' %}" method='post'>
    {% csrf_token %}
    {{form}}
    <input type="submit" name="Update Password">
</form>

health/templates/health/pop-up-profile.html
<!-- Profile user pop up -->
<div class="pop-up__box" id="pop-up-profile">
    <div class="pop-up" >

        <div class="pop-up__header">
            <h2 class="heading-secondary">{{ request.user.profile.user }}</h2>
            <span class="pop-up__header--close pop-up-close" data-popup="pop-up-profile"></span>
        </div>

        <form action="" class="pop-up__form">

            <div class="pop-up__form__info">
                <h4 class="pop-up__title">First Name:</h4>
                <span class="pop-up__stats">{{ request.user.profile.first_name }}</span>
            </div>

            <div class="pop-up__form__info">
                <h4 class="pop-up__title">Last Name:</h4>
                <span class="pop-up__stats">{{ request.user.profile.last_name }}</span>
            </div>

            <div class="pop-up__form__info">
                <h4 class="pop-up__title">Age:</h4>
                <span class="pop-up__stats">{{ request.user.profile.age }}</span>
            </div>

            <div class="pop-up__form__info">
                <h4 class="pop-up__title">Height:</h4>
                <span class="pop-up__stats">{{ request.user.profile.height | floatformat }}cm</span>
            </div>

            <div class="pop-up__form__info">
                <h4 class="pop-up__title">Weight</h4>
                <span class="pop-up__stats">{{ request.user.profile.weight | floatformat }} Kg</span>
            </div>

            <div class="pop-up__form__info">
                <h4 class="pop-up__title">Weight Goal:</h4>
                <span class="pop-up__stats">{{ request.user.profile.weight_goal }} Kg</span>
            </div>
            
            <input type="submit" class="btn-submit display-hide">

        </form>

        <div class="pop-up__update">
            <a href="{% url 'health:update_profile' %}" class="btn btn--juicy">Update Profile</a>

        </div>
        

    </div>
</div>